apache/dubbo-go-samples

.integration/testing/.travis.yml
.integration/testing/integration_testing.sh
.travis.yml
direct/dubbo/.travis.yml
gen_integrate_test.sh
metric/dubbo/.travis.yml
metric/dubbo/go-client/app/client.go
metric/dubbo/go-client/integration_testing.sh
metric/dubbo/go-server/integration_testing.sh

Add auto generate test script and test it in metric/dubbo

Ftr:Add auto generate test script and test it in metric/dubbo

---

build/Makefile

fix integration

---

general/grpc/protobuf/helloworld.pb.go
go.mod
go.sum

change grpc versin to 1.26.0
change sentinal version to 0.6.2

fix: change grpc and sentinel version

---

general/grpc/stream/go-server/app/server.go

fix: grpc stream bug

---

attachment/README.md
attachment/README_zh.md
attachment/go-client/cmd/client.go
attachment/go-client/conf/client.yml
attachment/go-client/conf/log.yml
attachment/go-client/pkg/user.go
attachment/go-server/cmd/server.go
attachment/go-server/conf/client.yml
attachment/go-server/conf/log.yml
attachment/go-server/conf/server.yml
attachment/go-server/docker/docker-compose.yml
attachment/go-server/pkg/user.go
attachment/go-server/tests/integration/main_test.go
attachment/go-server/tests/integration/userprovider_test.go

a sample to show how to use attachment in dubbo-go

add attachment sample

---

go.mod
go.sum

change to 1.5 branch commit https://github.com/apache/dubbo-go/commit/9c3bd0e9c92d70698f08f0ed4f81c8369a8346b6 to auto test by github-action

update dubbogo to 1.5 latest commit

---

helloworld/go-client/cmd/client.go
helloworld/go-server/cmd/server.go
helloworld/go-server/pkg/user.go
helloworld/go-server/tests/integration/main_test.go

fix: issue#71

---

.run/multi-registry/multi-registry-go-client.run.xml
.run/multi-registry/multi-registry-go-server.run.xml
go.mod
multi-registry/README.md
multi-registry/README_zh.md
multi-registry/go-client/cmd/client.go
multi-registry/go-client/conf/client.yml
multi-registry/go-server/cmd/server.go
multi-registry/go-server/conf/server.yml
multi-registry/go-server/docker/docker-compose.yml

add:multi registry

---

registry/nacos/go-client/cmd/client.go
registry/nacos/go-client/conf/client.yml
registry/nacos/go-server/cmd/server.go
registry/nacos/go-server/conf/server.yml

修改:修复registry/nacos示例无法正常使用的问题

---

configcenter/README.md
configcenter/README_zh.md
configcenter/zookeeper/go-client/conf/client.yml
configcenter/zookeeper/go-server/conf/client.yml
configcenter/zookeeper/go-server/conf/server.yml

fix zk configcenter can not found zk node err

1. fix zk configcenter can not found zk node

---

multi-registry/go-server/conf/client.yml
start_integrate_test.sh

Fix  multi registry (#1)

---

registry/etcd/go-server/docker/docker-compose.yml
start_integrate_test.sh

- add etcd integrate test
- remove etcd docker params

add etcd integrate test

---

.run/seata/seata_client_app.run.xml
.run/seata/seata_order-svc_app.run.xml
.run/seata/seata_product-svc_app.run.xml
seata/client/app/svc/svc.go
seata/order-svc/app/order_svc.go
seata/product-svc/app/product_svc.go

fix seata sample, make it work properly

fix: fix seata sample, make it work properly

---

README.md
README_zh.md
openzipkin/README.md
openzipkin/README_zh.md

Topic:  improving README 
- add `openzipkin`,`version` intro to dubbo-go readme 
- fix quote of `openzipkin` readme

Doc: improving README

---

.run/tengine/tengine-go-server.run.xml
README.md
README_zh.md
go.mod
tengine/README.md
tengine/README_zh.md
tengine/go-server/cmd/server.go
tengine/go-server/conf/client.yml
tengine/go-server/conf/log.yml
tengine/go-server/conf/server.yml
tengine/go-server/docker/docker-compose.yml
tengine/go-server/docker/tengine/nginx.conf
tengine/go-server/pkg/user.go

Topic: Tengine Calls Dubbo-go Example
Desc:
- a simple sample that Tengine Calls Dubbo-go Provider
- Chinese and English of the README
- .run config

Ftr: Tengine Calls Dubbo-go Example

---

seata/client/app/client.go
seata/client/app/svc/svc.go
seata/order-svc/app/dao/dao.go
seata/order-svc/app/order_svc.go
seata/order-svc/app/server.go
seata/product-svc/app/product_svc.go
seata/product-svc/app/server.go

fix: seata panic , attachment to AttachmentKey

Fix: seata panic , attachment to AttachmentKey

---

router/uniform-router/file/go-client/cmd/client.go

hessian.RegisterPOJO(&pkg.User{}) 重复调用

hessian.RegisterPOJO(&pkg.User{}) 重复调用

---

chain/build/test.sh
integrate_test.sh
multi-zone/build/test.sh
start_integrate_test.sh

Support custom integration tests how to start by editing path/to/example/build/test.sh

Ftr: Add integration test multi-server support

---

HOWTO.md

Doc: Update path to fit the project structure for HOWTO

---

async/go-server/tests/integration/userprovider_test.go

remove files

---

.run/service-discovery/discovery-nacos-go-client.run.xml

add service-discovery .run

---

helloworld/java-client/src/main/java/org/apache/dubbo/User.java
helloworld/java-server/src/main/java/org/apache/dubbo/User.java

fix dubbo-go sample java client and server User pojo id to ID

fix java User pojo id to ID

---

build/Makefile
integrate_test.sh
integrate_test/helloworld/docker/docker-health-check.sh
integrate_test/helloworld/tests/integration/userprovider_test.go
start_integrate_test.sh

support new integrate_test for config-enhance

Ftr: support new integrate_test in new dubbo samples

---

.run/triple-msgpack-client.run.xml
.run/triple-msgpack-server.run.xml
integrate_test/rpc/triple/msgpack/tests/integration/main_test.go
integrate_test/rpc/triple/msgpack/tests/integration/userprovider_test.go
rpc/triple/msgpack/go-client/cmd/client.go
rpc/triple/msgpack/go-client/conf/dubbogo.yml
rpc/triple/msgpack/go-server/cmd/server.go
rpc/triple/msgpack/go-server/conf/dubbogo.yml
start_integrate_test.sh

feat: add msgpack intrgrate test

---

generic/README.md
generic/README_zh.md

What's new:
- update documentation for the sample of generic invocation, both for English and Chinese version.

docs(geninv): update docs

---

.run/logger-custom.run.xml
logger/README.md
logger/README_zh.md
logger/custom/cmd/main.go
logger/custom/conf/dubbogo.yml

* 自定义 logger 样例
* custom logger .run 配置文件
* 更新 README

Ftr: custom logger sample

---

game/go-server-game/cmd/server.go
game/go-server-game/pkg/consumer.go
game/go-server-game/pkg/provider.go
game/go-server-gate/cmd/server.go
game/go-server-gate/pkg/consumer.go
game/go-server-gate/pkg/provider.go
integrate_test/game/go-server-game/tests/integration/main_test.go
integrate_test/game/go-server-gate/tests/integration/main_test.go
logger/custom/cmd/main.go

修复如下问题
* game 的集成测试导入了 cmd 包，pr 将其换为 pkg 包
* cusom logger fmt.Sprintf 第二个可变参数使用不规范

Fix: go vet error in game sample&custom logger sample

---

context/dubbo/go-client/cmd/client.go
context/dubbo/go-server/cmd/server.go
game/pkg/pojo/info.go
game/pkg/pojo/result.go
go.mod
go.sum
integrate_test/configcenter/nacos/tests/integration/main_test.go
integrate_test/rpc/dubbo/tests/integration/main_test.go
registry/etcd/go-client/pkg/user.go
registry/etcd/go-server/pkg/user.go
tracing/dubbo/go-client/pkg/user.go
tracing/dubbo/go-server/pkg/user.go

fix dubbo-go upgrade hessian 1.9.4 fail

update hessian1.10.0 integration test failed

---

skywalking/README.md
skywalking/README_zh.md

add skywalking example

---

rpc/grpc/protobuf/protobuf.mk

1. 升级插件:protoc-gen-dubbo to protoc-gen-dubbo3grpc
2. protoc命令更新,使用插件dubbo3grpc

更新dubbo3grpc generator使用文档

---

helloworld/java-client/pom.xml
helloworld/java-client/src/main/java/com/apache/dubbo/sample/basic/ApiConsumer.java
helloworld/java-server/pom.xml
helloworld/java-server/src/main/java/com/apache/dubbo/sample/basic/ApiProvider.java
integrate_test/helloworld/tests/java/run.sh

The previous way has been deprecated and cannot work properly with the new service discovery model introduced in 3.0

Upgrade helloworld java sample

---

metrics/go-client/cmd/client.go
metrics/go-client/conf/dubbogo.yml
metrics/go-server/cmd/server.go
metrics/go-server/conf/dubbogo.yml

PRs:
- [https://github.com/apache/dubbo-go/pull/2392](https://github.com/apache/dubbo-go/pull/2392)
TODO:
- Offer api to let users custom some metrics, dubbo-go metrics module needs to add this feature first.

refactor: update metrics sample to fit new design in dubbo-go
